version: "3.9"  

services:
  web:
    build: .  
    ports:
      - "8000:8000"  
    image: boluwatiiife/fastapiwithnginx:latest 
    container_name: fastapi-app 
    restart: unless-stopped  
    depends_on:
      - nginx 

  nginx:
    image: nginx:latest  
    ports:
      - "80:80"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - web 
    restart: unless-stopped
